##--------------------------------------------------------------------------------------##
############ Ansible-Roles used to publish the static content using roles      ###########
##                                                                                      ##
## 1) Check httpd package aviable on remote-traget hosts                                ## 
## 2) Check the status of the server                                                    ##
## 3) Step 1) Backup the file on remote-traget machine                                  ##
## 4) Step 2) Deploy the static content to remote-target servers                        ##
## 5) Step 3) Taking extra backup from remote-traget servers to local Control machines  ##
## 6) Step 4) Check the syntax after deploying the content                              ##
## 7) Step 5) All checks are 'ok' Stop & Start the apache web server                    ##
## 8) Step 6) Perform the basic check-out using 'uri' module to confirm content loading ##
##                                                  Vesion 1.0 > Authour by:Chandan     ##
##--------------------------------------------------------------------------------------##


---
- hosts: all
  roles: 
        - common
        - apache
