---
# Main Call : >> Checking webserver up/down -- Status
- name: Check httpd process running ...........
  shell: " ps -aef | grep apache | grep -v grep  | wc -l "
  register: counts
  changed_when: counts.stdout >= "5"

  notify:
     - syntax-check

- name: Deploy the static contents
  shell: " ps -aef | grep apache | grep -v grep  | wc -l "
  notify:
     - static-deployment

- name: --- Post-Check --- Syntax & restart Webserver Else revert the old version
  shell: " ps -aef | grep apache | grep -v grep  | wc -l "
  register: result
  ignore_errors: True
  notify:
     - syntax-check
     - start-apache


